# This script is executed by the `uninstall` target.
# It is not intended to be executed manually.
if [ -f install_manifest.txt ]
then
    for file_name in $(cat install_manifest.txt)
    do
        if [ -f $file_name ]
        then
            echo "removing: \`$file_name\`"
            rm $file_name
        else
            echo "not found: \`$file_name\`"
        fi
    done
else
    echo "error: could not find \`install_manifest.txt\`, which should be generated by \`make install\`"
    exit 1
fi
