/*! \file config.hpp Workaround for including a CMake-configured file in installation.
 *
 * This file provides variables configured by CMake.
 * When header files are actually installed, it is overwritten by `hexed_config.hpp`,
 * which CMake derives from \ref hexed_config.hpp.in.
 * This is to solve the following problem:
 * - CMake must place any autogenerated files in the build directory.
 * - However, other header files must include with quote syntax,
 *   preventing them from accessing the build directory.
 * This file allows the other headers to access the configuration file in the build directory
 * without causing problems once the headers are actually installed.
 */
#include <hexed_config.hpp>
