name: build_test


on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dbuild_tests=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: test/unit
